# Generated by Django 5.0.1 on 2024-01-11 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pagetype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageType",
        ),
    ]
