# Generated by Django 5.0.1 on 2024-01-12 01:48

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_pagetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())], use_json_field=True
            ),
        ),
    ]
