# Generated by Django 4.2.9 on 2024-01-16 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_blogpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="BlogPage",
        ),
        migrations.DeleteModel(
            name="StandardPage",
        ),
    ]
