# Generated by Django 4.2.9 on 2024-01-29 02:29

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_standardpage_page_ptr_delete_blogpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
