# Generated by Django 4.2.9 on 2024-02-06 05:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("core", "0010_filemodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="documentPage",
            new_name="ContentBlock",
        ),
    ]
