# Generated by Django 5.0.1 on 2024-02-19 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_documentpage_contentblock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentblock",
            old_name="subtitle",
            new_name="tag",
        ),
    ]
